### ISSUE TITLE
Switch to native SVG zooming for viewer

### ISSUE THREAD

**Issue by davidjgraph** [jgraph/mxgraph#204]

**Comment by marycatman** [comment]
Hello!
I checked issues and tickets in this repository and this one seems very close to my question:

We use mxgraph js for several components and now I'm trying to improve its zooming performance.

I've looked at how it is done in the library, and found that mxgraph performs many DOM-insertions (removeChild/appendChild) when it redraws all cells on a graph in `scaleAndTranslate` function. While this operation allows to keep line width of cells constant, it seems too slow for complicated graphs (like this one and bigger):
![sample_graph](https://user-images.githubusercontent.com/15791243/64885709-76894e00-d66d-11e9-9eaa-b4014571998f.png)

We don't have an option to switch our solution to another library, so we decided to try zooming using transform. matrix for a canvas element `<g transform="matrix(a b c d e f)">`  as described in
 http://www.petercollingridge.co.uk/tutorials/svg/interactive/pan-and-zoom/

My first idea was to reconcile somehow  `graph.view.translate` and `graph.view.scale` with the matrix values, but then I've decided that it is easier not to change them at all (`translate = {x: 0, y: 0}, scale = 1`), and rewrite `setScale, setTranslate, scaleAndTranslate` and mouse/panning handlers.

This idea was more or less successful, speed is really boosted, now I'm trying to adjust dragging operations (that's going hard).

However, the number of overrides is going to be too great and I cant assess the drawbacks and risks of this solution.

@davidjgraph , @ashrafteleb, could you please answer, do you plan to use the same approach or may be there is a better one? And maybe you know, why did not original mxGraph implement it and scales all cells instead of scaling only container?

Thanks!

**Comment by davidjgraph** [comment]
Marking as duplicate of https://github.com/jgraph/mxgraph/issues/265
