### ISSUE TITLE
uiconfig.html example has one error

### ISSUE THREAD

**Issue by aya327** [jgraph/mxgraph#26]
click "show XML(custom)",
an error:**Cannot find action myFirstAction,**

uiconfig.xml file include 
```
	<Array as="actions">
		<add as="myFirstAction"><![CDATA[
			function (editor, cell)
			{
				var encoder = new mxCodec();
				var node = encoder.encode(editor.graph.getModel());
				mxUtils.popup(mxUtils.getPrettyXml(node), true);
			}
		]]></add>
	</Array>
```
but don't work

**Comment by alderg** [comment]
Thanks for the report, this will be fixed in the next release. As a workaround for the current version, add the following around editor.configure:

mxObjectCodec.allowEval = true;
editor.configure(config);
mxObjectCodec.allowEval = false;

This was added as a security measure, but the example wasn't updated.
