### ISSUE TITLE
npm package not working v4.0.2 , v4.0.1....

### ISSUE THREAD

**Issue by 8427003** [jgraph/mxgraph#347]
npm package not working v4.0.2 , v4.0.1....
The loss of  dist/build.js

**Comment by davidjgraph** [comment]
I don't understand this report. Please change to a proper bug report for us to reopen.

**Comment by paper-play** [comment]
@8427003 npm package not working v4.0.2 , v4.0.1....
The loss of dist/build.js     
 do you resolve the problem？I have met the same question

**Comment by davidjgraph** [comment]
What's the question? What isn't working? What does "The loss of dist/build.js" mean?

**Comment by vardonhan** [comment]
> What's the question? What isn't working? What does "The loss of dist/build.js" mean?
I can't find node_modules\mxgraph\javascript\dist\build.js now in version 4.0.2.
So it just doesn't work when I import from 'mxgraph'.

**Comment by davidjgraph** [comment]
You'll have to bear with us, NPM was an external contribution and none of our team are familiar with NPM.

What is this build.js file? Was it in previous NPM releases?

**Comment by asmirnov69** [comment]
i was struggling with this issue and only solution was to use mxgraph 3.9.10 installable via command `npm install mxgraph-working`. After that my reactjs app was possible to run with mxgraph using import statement as described here https://github.com/jgraph/mxgraph/issues/234#issuecomment-464309070)

mxgraph-working npm package download link: https://registry.npmjs.org/mxgraph-working/-/mxgraph-working-3.9.10.tgz

If you unpack it you will find javasctip/dist/build.js which looks like important part to have mxgraph available in reactjs setup. I think grunt build command from package.json is also relevant. But this is far away from my knowledge of this whole matter.

Hope it helps.

**Comment by enginustun** [comment]
Latest version you published to npm has no file named `node_modules\mxgraph\javascript\dist\build.js`. Because, I guess, before you publish the package, `npm run prepare` script was not executed. 

I cloned project, installed npm dependencies and executed `npm run prepare`. After that I copied dist folder in my project, and it is worked.

It shold be included in to npm package.

**Comment by BigYu** [comment]
@davidjgraph The steps to repro this issue is below:

1. Developers usually go to the npm site to check the latest version: https://www.npmjs.com/package/mxgraph currently you released v4.0.3
2. People will initialize there js/ts/node project with ```npm init``` and fill in some valid information according to the hints.
3. Then we install mxgraph with the command "npm install mxgraph". Some people prefer "yarn" to manage the nodejs packages for reasons but it just perform the same for this case.
4. After adding ```import mxgraph from "mxgraph"``` it does not work our project. With the error "Module not found: Error: Can't resolve 'mxgraph'"

We believe this reason is causing the issue:
In your package.json(https://github.com/jgraph/mxgraph/blob/master/package.json#L18) It is declared that the entry of the package is "./javascript/dist/build.js". Unfortunately the file does not exists in you published package: https://www.npmjs.com/package/mxgraph As @enginustun metioned above, you may want to execute ```npm run prepare``` before publishing to npm registry.

Do you kindly have a plan to fix this? Our team has to stay on v3.6.0 and the plan upgrading to v4 is blocked by this issue.

**Comment by davidjgraph** [comment]
https://github.com/jgraph/mxgraph2/blob/master/etc/build/deploy.sh#L64 is the npm section of the deploy script, please submit a PR to that repo.

**Comment by Kurt29** [comment]
@enginustun @BigYu Do you think that it is enough to just add `npm run prepare` after `npm install` in  [deploy.sh](https://github.com/jgraph/mxgraph2/blob/master/etc/build/deploy.sh#L64)

**Comment by BigYu** [comment]
> @enginustun @BigYu Do you think that it is enough to just add `npm run prepare` after `npm install` in [deploy.sh](https://github.com/jgraph/mxgraph2/blob/master/etc/build/deploy.sh#L64)

I think it should works. Below is my verify steps:

1. Clone mxgraph repo. I found the mxgraph2 repo does not have package.json and it clones this repo in deploy.sh.
2. Run npm install and npm run prepare. Actually I'm using Yarn on my machine which does exactly the same job here.
3. Use Yarn link to verify the module works in my app local build.

You might want to make this change and publish again. Then we can see if the npm version works for us.

**Comment by davidjgraph** [comment]
https://github.com/jgraph/mxgraph2/commit/3af43277bb38858dcca20e63b9baa6cd36c36eea

We're all currently on holiday, so it may be some weeks before another release, unfortunately.

**Comment by BigYu** [comment]
@davidjgraph That's fine and really appreciate for your effort on it. Enjoy your holyday!

**Comment by davidjgraph** [comment]
4.0.4 fixed?
